#!/data/data/com.termux/files/usr/bin/sh
while true; do
	if pgrep -x 'wal'>/dev/null; then
		printf '\033[2J\033[H%s' "Getting Colors..."
	elif pgrep -x 'fastfetch '>/dev/null; then
		break
	else
		printf '"\033[2J\033[H%s' "Loading Something..."
	fi
done
